import { describe, it, expect } from 'vitest';
import { createBattle, CARD_POOL, getLegalMoves, applyMove } from './index.js';
const paddy=CARD_POOL['paddy-pimblett']!;
function fixture(){const s=createBattle({seed:12,deckP1:Array(20).fill(paddy),deckP2:Array(20).fill(CARD_POOL.merab!),energyTypeP1:'fire',energyTypeP2:'water'});s.phase={kind:'main'};s.turnPlayer='P1';s.turnNumber=4;s.players.P1.active!.damage=40;s.players.P1.active!.attached=['water','fire','fire'];return s;}
describe('Fattening Up',()=>{
 it('discards exactly one fire, heals 20, does not end the turn or mutate input',()=>{const s=fixture(),old=structuredClone(s);const n=applyMove(s,{type:'useAbility',targetUid:s.players.P1.active!.uid});expect(n.players.P1.active!.damage).toBe(20);expect(n.players.P1.active!.attached).toEqual(['water','fire']);expect(n.players.P1.discard.at(-1)).toEqual({kind:'energy',energy:'fire'});expect(n.turnPlayer).toBe('P1');expect(n.turnNumber).toBe(4);expect(n.events.at(-1)).toMatchObject({kind:'healed',amount:20});expect(s).toEqual(old);});
 it('caps healing at full HP',()=>{const s=fixture();s.players.P1.active!.damage=5;const n=applyMove(s,{type:'useAbility',targetUid:s.players.P1.active!.uid});expect(n.players.P1.active!.damage).toBe(0);expect(n.events.at(-1)).toMatchObject({amount:5});});
 it.each(['healthy','noFire','opponent','promotion','winner'])('rejects %s use',reason=>{const s=fixture();if(reason==='healthy')s.players.P1.active!.damage=0;if(reason==='noFire')s.players.P1.active!.attached=['water'];if(reason==='opponent')s.turnPlayer='P2';if(reason==='promotion')s.phase={kind:'awaitPromotion',player:'P1'};if(reason==='winner')s.winner='P1';expect(()=>applyMove(s,{type:'useAbility',targetUid:s.players.P1.active!.uid})).toThrow();});
 it('works on the bench, once per fighter, and retreat cannot reset usage',()=>{let s=fixture();const uid=s.players.P1.active!.uid;s.players.P1.bench=[{uid:'bench',card:paddy,attached:['fire','fire'],damage:50}];s=applyMove(s,{type:'useAbility',targetUid:'bench'});expect(getLegalMoves(s)).not.toContainEqual({type:'useAbility',targetUid:'bench'});expect(getLegalMoves(s)).toContainEqual({type:'useAbility',targetUid:uid});s=applyMove(s,{type:'retreat',benchIndex:0});expect(()=>applyMove(s,{type:'useAbility',targetUid:'bench'})).toThrow();});
 it('becomes available next own turn',()=>{let s=fixture(),uid=s.players.P1.active!.uid;s=applyMove(s,{type:'useAbility',targetUid:uid});s=applyMove(s,{type:'pass'});s=applyMove(s,{type:'pass'});expect(getLegalMoves(s)).toContainEqual({type:'useAbility',targetUid:uid});});
});
