import { describe, expect, it } from 'vitest';
import { CARD_POOL, applyMove, createBattle, getLegalMoves, computeDamage } from './index.js';
import { nextFloat } from './rng.js';
const charles=CARD_POOL['charles-oliveira']!, bronx=CARD_POOL['do-bronx']!;
function fixture(){const s=createBattle({seed:12,deckP1:Array(20).fill(charles),deckP2:Array(20).fill({...CARD_POOL.merab!,hp:500}),energyTypeP1:'lightning',energyTypeP2:'fire'});s.turnPlayer='P1';s.turnNumber=4;s.phase={kind:'main'};s.players.P1.active!.attached=['lightning'];s.players.P1.hand=[bronx];s.players.P2.active!.attached=['fire'];return s;}
describe('fighter evolution',()=>{
 it.each(['active','bench'])('evolves %s while preserving damage, energy and identity', slot=>{const s=fixture();const target=s.players.P1.active!;target.damage=20;if(slot==='bench'){s.players.P1.bench=[target];s.players.P1.active={...target,uid:'other',card:CARD_POOL.merab!};}const old=structuredClone(s);const move={type:'evolve' as const,handIndex:0,targetUid:target.uid};expect(getLegalMoves(s)).toContainEqual(move);const n=applyMove(s,move);const evolved=slot==='active'?n.players.P1.active!:n.players.P1.bench[0]!;expect(evolved).toMatchObject({uid:target.uid,card:bronx,damage:20,attached:['lightning'],previousStages:[charles]});expect(n.players.P1.hand).toHaveLength(0);expect(s).toEqual(old);});
 it('rejects first-turn, newly played and unrelated targets',()=>{const s=fixture();s.turnNumber=2;expect(getLegalMoves(s).some(m=>m.type==='evolve')).toBe(false);s.turnNumber=4;s.players.P1.active!.enteredTurn=4;expect(getLegalMoves(s).some(m=>m.type==='evolve')).toBe(false);s.players.P1.active!.enteredTurn=1;s.players.P1.active!.card=CARD_POOL.merab!;expect(()=>applyMove(s,{type:'evolve',handIndex:0,targetUid:s.players.P1.active!.uid})).toThrow();});
 it('discards every evolution stage on knockout',()=>{let s=fixture();s=applyMove(s,{type:'evolve',handIndex:0,targetUid:s.players.P1.active!.uid});s.players.P1.active!.damage=bronx.hp-10;s.turnPlayer='P2';const n=applyMove(s,{type:'attack',attackId:'single-leg'});expect(n.players.P1.discard.filter(x=>x.kind==='fighter').map(x=>x.card.id)).toEqual(['do-bronx','charles-oliveira']);});
});
describe('Pull Guard',()=>{
 it('does no damage and reduces the next opposing attack by 10, then expires',()=>{let s=fixture();s=applyMove(s,{type:'attack',attackId:'pull-guard'});expect(s.players.P2.active!.damage).toBe(0);expect(s.players.P1.active!.damageReduction).toBe(10);s=applyMove(s,{type:'attack',attackId:'single-leg'});expect(s.players.P1.active!.damage).toBe(10);expect(s.players.P1.active!.damageReduction).toBe(0);});
 it('expires even if the opponent passes',()=>{let s=applyMove(fixture(),{type:'attack',attackId:'pull-guard'});s=applyMove(s,{type:'pass'});expect(s.players.P1.active!.damageReduction).toBe(0);});
 it('reduces damage after weakness and never below zero',()=>{const s=fixture(),a=s.players.P2.active!,d=s.players.P1.active!;d.card={...charles,weakness:'colorless'};d.damageReduction=10;expect(computeDamage(a,d,a.card.attacks[0]!)).toBe(30);d.damageReduction=100;expect(computeDamage(a,d,a.card.attacks[0]!)).toBe(0);});
});
describe('Rear-Naked Choke',()=>{
 it.each([0,1,2,3])('flips exactly once with seed %i',seed=>{const s=fixture();s.players.P1.active!.card=bronx;s.players.P1.active!.attached=['lightning','lightning','fire'];s.rngState=seed;const roll=nextFloat(seed);const n=applyMove(s,{type:'attack',attackId:'rear-naked-choke'});expect(n.players.P2.active!.damage).toBe(roll.value<.5?110:60);expect(n.events.filter(e=>e.kind==='coinFlipped')).toHaveLength(1);expect(n.rngState).toBe(roll.state);});
 it('requires two electric and one additional energy',()=>{const s=fixture();s.players.P1.active!.card=bronx;s.players.P1.active!.attached=['lightning','fire','fire'];expect(getLegalMoves(s)).not.toContainEqual({type:'attack',attackId:'rear-naked-choke'});expect(getLegalMoves(s)).toContainEqual({type:'attack',attackId:'calf-kick'});});
});
